version: '3.8'

services:
  # FastAPI (server) service
  server:
    container_name: fastapi_server
    build:
      context: ./server
      dockerfile: Dockerfile
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      DATABASE_URL: "postgresql://vijayselvaraj:password@postgres:5432/testdb"
      POETRY_VIRTUALENVS_CREATE: "false"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy  # Ensures Postgres is ready before running migrations

  # Vite app service
  vite_app:
    container_name: vite_app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
      - postgres

  # PostgreSQL service
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: vijayselvaraj
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vijayselvaraj", "-d", "testdb"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:
